// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package testclient

import (
	"net/http"

	"github.com/Yamashou/gqlgenc/client"
	"go.infratographer.com/server-api/internal/ent/generated"
)

type TestClient interface {
}

type Client struct {
	Client *client.Client
}

func NewClient(cli *http.Client, baseURL string, options ...client.HTTPRequestOption) TestClient {
	return &Client{Client: client.NewClient(cli, baseURL, options...)}
}

type Query struct {
	ServerChassis       ServerChassis       "json:\"serverChassis\" graphql:\"serverChassis\""
	ServerChassisType   ServerChassisType   "json:\"serverChassisType\" graphql:\"serverChassisType\""
	ServerComponent     ServerComponent     "json:\"serverComponent\" graphql:\"serverComponent\""
	ServerComponentType ServerComponentType "json:\"serverComponentType\" graphql:\"serverComponentType\""
	ServerCPU           ServerCPU           "json:\"serverCPU\" graphql:\"serverCPU\""
	ServerCPUType       ServerCPUType       "json:\"serverCPUType\" graphql:\"serverCPUType\""
	ServerProvider      generated.Provider  "json:\"serverProvider\" graphql:\"serverProvider\""
	Server              Server              "json:\"server\" graphql:\"server\""
	ServerType          ServerType          "json:\"serverType\" graphql:\"serverType\""
	Entities            []Entity            "json:\"_entities\" graphql:\"_entities\""
	Service             Service             "json:\"_service\" graphql:\"_service\""
}
type Mutation struct {
	ServerChassis             ServerChassisCreatePayload       "json:\"serverChassis\" graphql:\"serverChassis\""
	ServerChassisUpdate       ServerChassisUpdatePayload       "json:\"serverChassisUpdate\" graphql:\"serverChassisUpdate\""
	ServerChassisDelete       ServerChassisDeletePayload       "json:\"serverChassisDelete\" graphql:\"serverChassisDelete\""
	ServerChassisType         ServerChassisTypeCreatePayload   "json:\"serverChassisType\" graphql:\"serverChassisType\""
	ServerChassisTypeUpdate   ServerChassisTypeUpdatePayload   "json:\"serverChassisTypeUpdate\" graphql:\"serverChassisTypeUpdate\""
	ServerChassisTypeDelete   ServerChassisTypeDeletePayload   "json:\"serverChassisTypeDelete\" graphql:\"serverChassisTypeDelete\""
	ServerComponentCreate     ServerComponentCreatePayload     "json:\"serverComponentCreate\" graphql:\"serverComponentCreate\""
	ServerComponentUpdate     ServerComponentUpdatePayload     "json:\"serverComponentUpdate\" graphql:\"serverComponentUpdate\""
	ServerComponentDelete     ServerComponentDeletePayload     "json:\"serverComponentDelete\" graphql:\"serverComponentDelete\""
	ServerComponentTypeCreate ServerComponentTypeCreatePayload "json:\"serverComponentTypeCreate\" graphql:\"serverComponentTypeCreate\""
	ServerComponentTypeUpdate ServerComponentTypeUpdatePayload "json:\"serverComponentTypeUpdate\" graphql:\"serverComponentTypeUpdate\""
	ServerComponentTypeDelete ServerComponentTypeDeletePayload "json:\"serverComponentTypeDelete\" graphql:\"serverComponentTypeDelete\""
	ServerCPU                 ServerCPUCreatePayload           "json:\"serverCPU\" graphql:\"serverCPU\""
	ServerCPUUpdate           ServerCPUUpdatePayload           "json:\"serverCPUUpdate\" graphql:\"serverCPUUpdate\""
	ServerCPUDelete           ServerCPUDeletePayload           "json:\"serverCPUDelete\" graphql:\"serverCPUDelete\""
	ServerCPUType             ServerCPUTypeCreatePayload       "json:\"serverCPUType\" graphql:\"serverCPUType\""
	ServerCPUTypeUpdate       ServerCPUTypeUpdatePayload       "json:\"serverCPUTypeUpdate\" graphql:\"serverCPUTypeUpdate\""
	ServerCPUTypeDelete       ServerCPUTypeDeletePayload       "json:\"serverCPUTypeDelete\" graphql:\"serverCPUTypeDelete\""
	ServerProviderCreate      ServerProviderCreatePayload      "json:\"serverProviderCreate\" graphql:\"serverProviderCreate\""
	ServerProviderUpdate      ServerProviderUpdatePayload      "json:\"serverProviderUpdate\" graphql:\"serverProviderUpdate\""
	ServerProviderDelete      ServerProviderDeletePayload      "json:\"serverProviderDelete\" graphql:\"serverProviderDelete\""
	ServerCreate              ServerCreatePayload              "json:\"serverCreate\" graphql:\"serverCreate\""
	ServerUpdate              ServerUpdatePayload              "json:\"serverUpdate\" graphql:\"serverUpdate\""
	ServerDelete              ServerDeletePayload              "json:\"serverDelete\" graphql:\"serverDelete\""
	ServerTypeCreate          ServerTypeCreatePayload          "json:\"serverTypeCreate\" graphql:\"serverTypeCreate\""
	ServerTypeUpdate          ServerTypeUpdatePayload          "json:\"serverTypeUpdate\" graphql:\"serverTypeUpdate\""
	ServerTypeDelete          ServerTypeDeletePayload          "json:\"serverTypeDelete\" graphql:\"serverTypeDelete\""
}
