package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"database/sql"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ServerChassis is the resolver for the serverChassis field.
func (r *mutationResolver) ServerChassis(ctx context.Context, input generated.CreateServerChassisInput) (*ServerChassisCreatePayload, error) {
	// TODO: check permissions

	ct, err := r.client.ServerChassis.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &ServerChassisCreatePayload{ServerChassis: ct}, nil
}

// ServerChassisUpdate is the resolver for the serverChassisUpdate field.
func (r *mutationResolver) ServerChassisUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerChassisInput) (*ServerChassisUpdatePayload, error) {
	// TODO: check permissions

	ct, err := r.client.ServerChassis.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	ct, err = ct.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &ServerChassisUpdatePayload{ServerChassis: ct}, nil
}

// ServerChassisDelete is the resolver for the serverChassisDelete field.
func (r *mutationResolver) ServerChassisDelete(ctx context.Context, id gidx.PrefixedID) (*ServerChassisDeletePayload, error) {
	//TODO: check permissions

	tx, err := r.client.BeginTx(ctx, &sql.TxOptions{})
	if err != nil {
		return nil, err
	}

	if err := tx.ServerChassis.DeleteOneID(id).Exec(ctx); err != nil {
		r.logger.Errorw("failed to commit transaction", "error", err)
		if rerr := tx.Rollback(); rerr != nil {
			r.logger.Errorw("failed to rollback transaction", "error", rerr, "stage", "delete chassis")
		}
		return nil, err
	}

	if err := tx.Commit(); err != nil {
		r.logger.Errorw("failed to commit transaction", "error", err)
		if rerr := tx.Rollback(); rerr != nil {
			r.logger.Errorw("failed to rollback transaction", "error", rerr, "stage", "commit transaction")
		}
		return nil, err
	}

	return &ServerChassisDeletePayload{DeletedID: id}, nil
}

// ServerChassis is the resolver for the serverChassis field.
func (r *queryResolver) ServerChassis(ctx context.Context, id gidx.PrefixedID) (*generated.ServerChassis, error) {
	return r.client.ServerChassis.Get(ctx, id)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
