package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"database/sql"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/server-api/internal/ent/generated/predicate"
	"go.infratographer.com/server-api/internal/ent/generated/serverchassis"
	"go.infratographer.com/x/gidx"
)

// ServerChassisType is the resolver for the serverChassisType field.
func (r *mutationResolver) ServerChassisType(ctx context.Context, input generated.CreateServerChassisTypeInput) (*ServerChassisTypeCreatePayload, error) {
	// TODO: check permissions

	ct, err := r.client.ServerChassisType.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &ServerChassisTypeCreatePayload{ServerChassisType: ct}, nil
}

// ServerChassisTypeUpdate is the resolver for the serverChassisTypeUpdate field.
func (r *mutationResolver) ServerChassisTypeUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerChassisTypeInput) (*ServerChassisTypeUpdatePayload, error) {
	// TODO: check permissions

	ct, err := r.client.ServerChassisType.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	ct, err = ct.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &ServerChassisTypeUpdatePayload{ServerChassisType: ct}, nil
}

// ServerChassisTypeDelete is the resolver for the serverChassisTypeDelete field.
func (r *mutationResolver) ServerChassisTypeDelete(ctx context.Context, id gidx.PrefixedID) (*ServerChassisTypeDeletePayload, error) {
	//TODO: check permissions

	tx, err := r.client.BeginTx(ctx, &sql.TxOptions{})
	if err != nil {
		return nil, err
	}

	// cleanup chassis associated with type
	chas, err := tx.ServerChassis.Query().Where(predicate.ServerChassis(serverchassis.ServerChassisTypeIDEQ(id))).All(ctx)
	if err != nil {
		r.logger.Errorw("failed to query components", "error", err)
		if rerr := tx.Rollback(); rerr != nil {
			r.logger.Errorw("failed to rollback transaction", "error", rerr, "stage", "query chassis")
		}
		return nil, err
	}

	for _, c := range chas {
		if err = tx.ServerChassis.DeleteOne(c).Exec(ctx); err != nil {
			r.logger.Errorw("failed to delete server", "port", c.ID, "error", err)
			if rerr := tx.Rollback(); rerr != nil {
				r.logger.Errorw("failed to rollback transaction", "error", rerr, "stage", "delete chassis")
			}
		}
	}

	if err := tx.ServerChassisType.DeleteOneID(id).Exec(ctx); err != nil {
		r.logger.Errorw("failed to commit transaction", "error", err)
		if rerr := tx.Rollback(); rerr != nil {
			r.logger.Errorw("failed to rollback transaction", "error", rerr, "stage", "delete chassis type")
		}
		return nil, err
	}

	if err := tx.Commit(); err != nil {
		r.logger.Errorw("failed to commit transaction", "error", err)
		if rerr := tx.Rollback(); rerr != nil {
			r.logger.Errorw("failed to rollback transaction", "error", rerr, "stage", "commit transaction")
		}
		return nil, err
	}

	return &ServerChassisTypeDeletePayload{DeletedID: id}, nil
}

// ServerChassisType is the resolver for the serverChassisType field.
func (r *queryResolver) ServerChassisType(ctx context.Context, id gidx.PrefixedID) (*generated.ServerChassisType, error) {
	return r.client.ServerChassisType.Get(ctx, id)
}
