package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ServerChassisType is the resolver for the serverChassisType field.
func (r *mutationResolver) ServerChassisType(ctx context.Context, input generated.CreateServerChassisTypeInput) (*ServerChassisTypeCreatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerChassisType - serverChassisType"))
}

// ServerChassisTypeUpdate is the resolver for the serverChassisTypeUpdate field.
func (r *mutationResolver) ServerChassisTypeUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerChassisTypeInput) (*ServerChassisTypeUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerChassisTypeUpdate - serverChassisTypeUpdate"))
}

// ServerChassisTypeDelete is the resolver for the serverChassisTypeDelete field.
func (r *mutationResolver) ServerChassisTypeDelete(ctx context.Context, id gidx.PrefixedID) (*ServerChassisTypeDeletePayload, error) {
	panic(fmt.Errorf("not implemented: ServerChassisTypeDelete - serverChassisTypeDelete"))
}

// ServerChassisType is the resolver for the serverChassisType field.
func (r *queryResolver) ServerChassisType(ctx context.Context, id gidx.PrefixedID) (*generated.ServerChassisType, error) {
	panic(fmt.Errorf("not implemented: ServerChassisType - serverChassisType"))
}
