package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ServerComponentCreate is the resolver for the serverComponentCreate field.
func (r *mutationResolver) ServerComponentCreate(ctx context.Context, input generated.CreateServerComponentInput) (*ServerComponentCreatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerComponentCreate - serverComponentCreate"))
}

// ServerComponentUpdate is the resolver for the serverComponentUpdate field.
func (r *mutationResolver) ServerComponentUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerComponentInput) (*ServerComponentUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerComponentUpdate - serverComponentUpdate"))
}

// ServerComponentDelete is the resolver for the serverComponentDelete field.
func (r *mutationResolver) ServerComponentDelete(ctx context.Context, id gidx.PrefixedID) (*ServerComponentDeletePayload, error) {
	panic(fmt.Errorf("not implemented: ServerComponentDelete - serverComponentDelete"))
}

// ServerComponent is the resolver for the serverComponent field.
func (r *queryResolver) ServerComponent(ctx context.Context, id gidx.PrefixedID) (*generated.ServerComponent, error) {
	panic(fmt.Errorf("not implemented: ServerComponent - serverComponent"))
}
