package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ServerCPU is the resolver for the serverCPU field.
func (r *mutationResolver) ServerCPU(ctx context.Context, input generated.CreateServerCPUInput) (*ServerCPUCreatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerCPU - serverCPU"))
}

// ServerCPUUpdate is the resolver for the serverCPUUpdate field.
func (r *mutationResolver) ServerCPUUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerCPUInput) (*ServerCPUUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerCPUUpdate - serverCPUUpdate"))
}

// ServerCPUDelete is the resolver for the serverCPUDelete field.
func (r *mutationResolver) ServerCPUDelete(ctx context.Context, id gidx.PrefixedID) (*ServerCPUDeletePayload, error) {
	panic(fmt.Errorf("not implemented: ServerCPUDelete - serverCPUDelete"))
}

// ServerCPU is the resolver for the serverCPU field.
func (r *queryResolver) ServerCPU(ctx context.Context, id gidx.PrefixedID) (*generated.ServerCPU, error) {
	panic(fmt.Errorf("not implemented: ServerCPU - serverCPU"))
}
