package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"database/sql"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/server-api/internal/ent/generated/predicate"
	"go.infratographer.com/server-api/internal/ent/generated/servercpu"
	"go.infratographer.com/x/gidx"
)

// ServerCPUType is the resolver for the serverCPUType field.
func (r *mutationResolver) ServerCPUType(ctx context.Context, input generated.CreateServerCPUTypeInput) (*ServerCPUTypeCreatePayload, error) {
	// TODO: check permissions

	ct, err := r.client.ServerCPUType.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &ServerCPUTypeCreatePayload{ServerCPUType: ct}, nil
}

// ServerCPUTypeUpdate is the resolver for the serverCPUTypeUpdate field.
func (r *mutationResolver) ServerCPUTypeUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerCPUTypeInput) (*ServerCPUTypeUpdatePayload, error) {
	// TODO: check permissions

	ct, err := r.client.ServerCPUType.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	ct, err = ct.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &ServerCPUTypeUpdatePayload{ServerCPUType: ct}, nil
}

// ServerCPUTypeDelete is the resolver for the serverCPUTypeDelete field.
func (r *mutationResolver) ServerCPUTypeDelete(ctx context.Context, id gidx.PrefixedID) (*ServerCPUTypeDeletePayload, error) {
	//TODO: check permissions

	tx, err := r.client.BeginTx(ctx, &sql.TxOptions{})
	if err != nil {
		return nil, err
	}

	// cleanup cpus associated with type
	cpus, err := tx.ServerCPU.Query().Where(predicate.ServerCPU(servercpu.ServerCPUTypeIDEQ(id))).All(ctx)
	if err != nil {
		r.logger.Errorw("failed to query cpus", "error", err)
		if rerr := tx.Rollback(); rerr != nil {
			r.logger.Errorw("failed to rollback transaction", "error", rerr, "stage", "query cpus")
		}
		return nil, err
	}

	for _, c := range cpus {
		if err = tx.ServerCPU.DeleteOne(c).Exec(ctx); err != nil {
			r.logger.Errorw("failed to delete server", "port", c.ID, "error", err)
			if rerr := tx.Rollback(); rerr != nil {
				r.logger.Errorw("failed to rollback transaction", "error", rerr, "stage", "delete cpu")
			}
		}
	}

	if err := tx.ServerCPUType.DeleteOneID(id).Exec(ctx); err != nil {
		r.logger.Errorw("failed to commit transaction", "error", err)
		if rerr := tx.Rollback(); rerr != nil {
			r.logger.Errorw("failed to rollback transaction", "error", rerr, "stage", "delete server cpu type")
		}
		return nil, err
	}

	if err := tx.Commit(); err != nil {
		r.logger.Errorw("failed to commit transaction", "error", err)
		if rerr := tx.Rollback(); rerr != nil {
			r.logger.Errorw("failed to rollback transaction", "error", rerr, "stage", "commit transaction")
		}
		return nil, err
	}

	return &ServerCPUTypeDeletePayload{DeletedID: id}, nil
}

// ServerCPUType is the resolver for the serverCPUType field.
func (r *queryResolver) ServerCPUType(ctx context.Context, id gidx.PrefixedID) (*generated.ServerCPUType, error) {
	return r.client.ServerCPUType.Get(ctx, id)
}
