// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphapi

import (
	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// Return response from serverCPUCreate
type ServerCPUCreatePayload struct {
	// The created server cpu.
	ServerCPU *generated.ServerCPU `json:"serverCPU"`
}

// Return response from serverCPUDelete
type ServerCPUDeletePayload struct {
	// The ID of the deleted server cpu.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverCPUTypeCreate
type ServerCPUTypeCreatePayload struct {
	// The created server cpu type.
	ServerCPUType *generated.ServerCPUType `json:"serverCPUType"`
}

// Return response from serverCPUTypeDelete
type ServerCPUTypeDeletePayload struct {
	// The ID of the deleted server cpu type.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverCPUTypeUpdate
type ServerCPUTypeUpdatePayload struct {
	// The updated server cpu type.
	ServerCPUType *generated.ServerCPUType `json:"serverCPUType"`
}

// Return response from serverCPUUpdate
type ServerCPUUpdatePayload struct {
	// The updated server cpu.
	ServerCPU *generated.ServerCPU `json:"serverCPU"`
}

// Return response from serverChassisCreate
type ServerChassisCreatePayload struct {
	// The created server chassis.
	ServerChassis *generated.ServerChassis `json:"serverChassis"`
}

// Return response from serverChassisDelete
type ServerChassisDeletePayload struct {
	// The ID of the deleted server chassis.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverChassisTypeCreate
type ServerChassisTypeCreatePayload struct {
	// The created server chassis type.
	ServerChassisType *generated.ServerChassisType `json:"serverChassisType"`
}

// Return response from serverChassisTypeDelete
type ServerChassisTypeDeletePayload struct {
	// The ID of the deleted server chassis type.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverChassisTypeUpdate
type ServerChassisTypeUpdatePayload struct {
	// The updated server chassis type.
	ServerChassisType *generated.ServerChassisType `json:"serverChassisType"`
}

// Return response from serverChassisUpdate
type ServerChassisUpdatePayload struct {
	// The updated server chassis.
	ServerChassis *generated.ServerChassis `json:"serverChassis"`
}

// Return response from serverComponentCreate
type ServerComponentCreatePayload struct {
	// The created server component.
	ServerComponent *generated.ServerComponent `json:"serverComponent"`
}

// Return response from serverComponentDelete
type ServerComponentDeletePayload struct {
	// The ID of the deleted server component.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverComponentTypeCreate
type ServerComponentTypeCreatePayload struct {
	// The created server component type.
	ServerComponentType *generated.ServerComponentType `json:"serverComponentType"`
}

// Return response from serverComponentTypeDelete
type ServerComponentTypeDeletePayload struct {
	// The ID of the deleted server component type.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverComponentTypeUpdate
type ServerComponentTypeUpdatePayload struct {
	// The updated server component type.
	ServerComponentType *generated.ServerComponentType `json:"serverComponentType"`
}

// Return response from serverComponentUpdate
type ServerComponentUpdatePayload struct {
	// The updated server component.
	ServerComponent *generated.ServerComponent `json:"serverComponent"`
}

// Return response from serverCreate
type ServerCreatePayload struct {
	// The created server.
	Server *generated.Server `json:"server"`
}

// Return response from serverDelete
type ServerDeletePayload struct {
	// The ID of the deleted server.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverHardDriveCreate
type ServerHardDriveCreatePayload struct {
	// The created server hard drive.
	ServerHardDrive *generated.ServerHardDrive `json:"serverHardDrive"`
}

// Return response from serverHardDriveDelete
type ServerHardDriveDeletePayload struct {
	// The ID of the deleted server hard drive.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverHardDriveTypeCreate
type ServerHardDriveTypeCreatePayload struct {
	// The created server hard drive type.
	ServerHardDriveType *generated.ServerHardDriveType `json:"serverHardDriveType"`
}

// Return response from serverHardDriveTypeDelete
type ServerHardDriveTypeDeletePayload struct {
	// The ID of the deleted server hard drive type.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverHardDriveTypeUpdate
type ServerHardDriveTypeUpdatePayload struct {
	// The updated server hard drive type.
	ServerHardDriveType *generated.ServerHardDriveType `json:"serverHardDriveType"`
}

// Return response from serverHardDriveUpdate
type ServerHardDriveUpdatePayload struct {
	// The updated server hard drive.
	ServerHardDrive *generated.ServerHardDrive `json:"serverHardDrive"`
}

// Return response from serverMemoryCreate
type ServerMemoryCreatePayload struct {
	// The created server memory.
	ServerMemory *generated.ServerMemory `json:"serverMemory"`
}

// Return response from serverMemoryDelete
type ServerMemoryDeletePayload struct {
	// The ID of the deleted server memory.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverMemoryTypeCreate
type ServerMemoryTypeCreatePayload struct {
	// The created server memory type.
	ServerMemoryType *generated.ServerMemoryType `json:"serverMemoryType"`
}

// Return response from serverMemoryTypeDelete
type ServerMemoryTypeDeletePayload struct {
	// The ID of the deleted server memory type.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverMemoryTypeUpdate
type ServerMemoryTypeUpdatePayload struct {
	// The updated server memory type.
	ServerMemoryType *generated.ServerMemoryType `json:"serverMemoryType"`
}

// Return response from serverMemoryUpdate
type ServerMemoryUpdatePayload struct {
	// The updated server memory.
	ServerMemory *generated.ServerMemory `json:"serverMemory"`
}

// Return response from serverMotherboardCreate
type ServerMotherboardCreatePayload struct {
	// The created server motherboard.
	ServerMotherboard *generated.ServerMotherboard `json:"serverMotherboard"`
}

// Return response from serverMotherboardDelete
type ServerMotherboardDeletePayload struct {
	// The ID of the deleted server motherboard.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverMotherboardTypeCreate
type ServerMotherboardTypeCreatePayload struct {
	// The created server motherboard type.
	ServerMotherboardType *generated.ServerMotherboardType `json:"serverMotherboardType"`
}

// Return response from serverMotherboardTypeDelete
type ServerMotherboardTypeDeletePayload struct {
	// The ID of the deleted server motherboard type.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverMotherboardTypeUpdate
type ServerMotherboardTypeUpdatePayload struct {
	// The updated server motherboard type.
	ServerMotherboardType *generated.ServerMotherboardType `json:"serverMotherboardType"`
}

// Return response from serverMotherboardUpdate
type ServerMotherboardUpdatePayload struct {
	// The updated server motherboard.
	ServerMotherboard *generated.ServerMotherboard `json:"serverMotherboard"`
}

// Return response from serverNetworkCardCreate
type ServerNetworkCardCreatePayload struct {
	// The created server network card.
	ServerNetworkCard *generated.ServerNetworkCard `json:"serverNetworkCard"`
}

// Return response from serverNetworkCardDelete
type ServerNetworkCardDeletePayload struct {
	// The ID of the deleted server network card.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverNetworkCardTypeCreate
type ServerNetworkCardTypeCreatePayload struct {
	// The created server network card type.
	ServerNetworkCardType *generated.ServerNetworkCardType `json:"serverNetworkCardType"`
}

// Return response from serverNetworkCardTypeDelete
type ServerNetworkCardTypeDeletePayload struct {
	// The ID of the deleted server network card type.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverNetworkCardTypeUpdate
type ServerNetworkCardTypeUpdatePayload struct {
	// The updated server network card type.
	ServerNetworkCardType *generated.ServerNetworkCardType `json:"serverNetworkCardType"`
}

// Return response from serverNetworkCardUpdate
type ServerNetworkCardUpdatePayload struct {
	// The updated server network card.
	ServerNetworkCard *generated.ServerNetworkCard `json:"serverNetworkCard"`
}

// Return response from serverNetworkPortCreate
type ServerNetworkPortCreatePayload struct {
	// The created server network port.
	ServerNetworkPort *generated.ServerNetworkPort `json:"serverNetworkPort"`
}

// Return response from serverNetworkPortDelete
type ServerNetworkPortDeletePayload struct {
	// The ID of the deleted server network port.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverNetworkPortUpdate
type ServerNetworkPortUpdatePayload struct {
	// The updated server network port.
	ServerNetworkPort *generated.ServerNetworkPort `json:"serverNetworkPort"`
}

// Return response from serverPowerSupplyCreate
type ServerPowerSupplyCreatePayload struct {
	// The created server power supply.
	ServerPowerSupply *generated.ServerPowerSupply `json:"serverPowerSupply"`
}

// Return response from serverPowerSupplyDelete
type ServerPowerSupplyDeletePayload struct {
	// The ID of the deleted server power supply.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverPowerSupplyTypeCreate
type ServerPowerSupplyTypeCreatePayload struct {
	// The created server power supply type.
	ServerPowerSupplyType *generated.ServerPowerSupplyType `json:"serverPowerSupplyType"`
}

// Return response from serverPowerSupplyTypeDelete
type ServerPowerSupplyTypeDeletePayload struct {
	// The ID of the deleted server power supply type.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverPowerSupplyTypeUpdate
type ServerPowerSupplyTypeUpdatePayload struct {
	// The updated server power supply type.
	ServerPowerSupplyType *generated.ServerPowerSupplyType `json:"serverPowerSupplyType"`
}

// Return response from serverPowerSupplyUpdate
type ServerPowerSupplyUpdatePayload struct {
	// The updated server power supply.
	ServerPowerSupply *generated.ServerPowerSupply `json:"serverPowerSupply"`
}

// Return response from serverProviderCreate
type ServerProviderCreatePayload struct {
	// The created server provider.
	ServerProvider *generated.Provider `json:"serverProvider"`
}

// Return response from serverProviderDelete
type ServerProviderDeletePayload struct {
	// The ID of the deleted server provider.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverProviderUpdate
type ServerProviderUpdatePayload struct {
	// The updated server provider.
	ServerProvider *generated.Provider `json:"serverProvider"`
}

// Return response from serverTypeCreate
type ServerTypeCreatePayload struct {
	// The created server type.
	ServerType *generated.ServerType `json:"serverType"`
}

// Return response from serverTypeDelete
type ServerTypeDeletePayload struct {
	// The ID of the deleted server type.
	DeletedID gidx.PrefixedID `json:"deletedID"`
}

// Return response from serverTypeUpdate
type ServerTypeUpdatePayload struct {
	// The updated server type.
	ServerType *generated.ServerType `json:"serverType"`
}

// Return response from serverUpdate
type ServerUpdatePayload struct {
	// The updated server.
	Server *generated.Server `json:"server"`
}
