package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ServerHardDrive is the resolver for the serverHardDrive field.
func (r *mutationResolver) ServerHardDrive(ctx context.Context, input generated.CreateServerHardDriveInput) (*ServerHardDriveCreatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerHardDrive - serverHardDrive"))
}

// ServerHardDriveUpdate is the resolver for the serverHardDriveUpdate field.
func (r *mutationResolver) ServerHardDriveUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerHardDriveInput) (*ServerHardDriveUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerHardDriveUpdate - serverHardDriveUpdate"))
}

// ServerHardDriveDelete is the resolver for the serverHardDriveDelete field.
func (r *mutationResolver) ServerHardDriveDelete(ctx context.Context, id gidx.PrefixedID) (*ServerHardDriveDeletePayload, error) {
	panic(fmt.Errorf("not implemented: ServerHardDriveDelete - serverHardDriveDelete"))
}

// ServerHardDrive is the resolver for the serverHardDrive field.
func (r *queryResolver) ServerHardDrive(ctx context.Context, id gidx.PrefixedID) (*generated.ServerHardDrive, error) {
	panic(fmt.Errorf("not implemented: ServerHardDrive - serverHardDrive"))
}
