package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ServerHardDriveType is the resolver for the serverHardDriveType field.
func (r *mutationResolver) ServerHardDriveType(ctx context.Context, input generated.CreateServerHardDriveTypeInput) (*ServerHardDriveTypeCreatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerHardDriveType - serverHardDriveType"))
}

// ServerHardDriveTypeUpdate is the resolver for the serverHardDriveTypeUpdate field.
func (r *mutationResolver) ServerHardDriveTypeUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerHardDriveTypeInput) (*ServerHardDriveTypeUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerHardDriveTypeUpdate - serverHardDriveTypeUpdate"))
}

// ServerHardDriveTypeDelete is the resolver for the serverHardDriveTypeDelete field.
func (r *mutationResolver) ServerHardDriveTypeDelete(ctx context.Context, id gidx.PrefixedID) (*ServerHardDriveTypeDeletePayload, error) {
	panic(fmt.Errorf("not implemented: ServerHardDriveTypeDelete - serverHardDriveTypeDelete"))
}

// ServerHardDriveType is the resolver for the serverHardDriveType field.
func (r *queryResolver) ServerHardDriveType(ctx context.Context, id gidx.PrefixedID) (*generated.ServerHardDriveType, error) {
	panic(fmt.Errorf("not implemented: ServerHardDriveType - serverHardDriveType"))
}
