package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ServerMemoryType is the resolver for the serverMemoryType field.
func (r *mutationResolver) ServerMemoryType(ctx context.Context, input generated.CreateServerMemoryTypeInput) (*ServerMemoryTypeCreatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerMemoryType - serverMemoryType"))
}

// ServerMemoryTypeUpdate is the resolver for the serverMemoryTypeUpdate field.
func (r *mutationResolver) ServerMemoryTypeUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerMemoryTypeInput) (*ServerMemoryTypeUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerMemoryTypeUpdate - serverMemoryTypeUpdate"))
}

// ServerMemoryTypeDelete is the resolver for the serverMemoryTypeDelete field.
func (r *mutationResolver) ServerMemoryTypeDelete(ctx context.Context, id gidx.PrefixedID) (*ServerMemoryTypeDeletePayload, error) {
	panic(fmt.Errorf("not implemented: ServerMemoryTypeDelete - serverMemoryTypeDelete"))
}

// ServerMemoryType is the resolver for the serverMemoryType field.
func (r *queryResolver) ServerMemoryType(ctx context.Context, id gidx.PrefixedID) (*generated.ServerMemoryType, error) {
	panic(fmt.Errorf("not implemented: ServerMemoryType - serverMemoryType"))
}
