package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ServerMemory is the resolver for the serverMemory field.
func (r *mutationResolver) ServerMemory(ctx context.Context, input generated.CreateServerMemoryInput) (*ServerMemoryCreatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerMemory - serverMemory"))
}

// ServerMemoryUpdate is the resolver for the serverMemoryUpdate field.
func (r *mutationResolver) ServerMemoryUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerMemoryInput) (*ServerMemoryUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerMemoryUpdate - serverMemoryUpdate"))
}

// ServerMemoryDelete is the resolver for the serverMemoryDelete field.
func (r *mutationResolver) ServerMemoryDelete(ctx context.Context, id gidx.PrefixedID) (*ServerMemoryDeletePayload, error) {
	panic(fmt.Errorf("not implemented: ServerMemoryDelete - serverMemoryDelete"))
}

// ServerMemory is the resolver for the serverMemory field.
func (r *queryResolver) ServerMemory(ctx context.Context, id gidx.PrefixedID) (*generated.ServerMemory, error) {
	panic(fmt.Errorf("not implemented: ServerMemory - serverMemory"))
}
