package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ServerMotherboardType is the resolver for the serverMotherboardType field.
func (r *mutationResolver) ServerMotherboardType(ctx context.Context, input generated.CreateServerMotherboardTypeInput) (*ServerMotherboardTypeCreatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerMotherboardType - serverMotherboardType"))
}

// ServerMotherboardTypeUpdate is the resolver for the serverMotherboardTypeUpdate field.
func (r *mutationResolver) ServerMotherboardTypeUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerMotherboardTypeInput) (*ServerMotherboardTypeUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerMotherboardTypeUpdate - serverMotherboardTypeUpdate"))
}

// ServerMotherboardTypeDelete is the resolver for the serverMotherboardTypeDelete field.
func (r *mutationResolver) ServerMotherboardTypeDelete(ctx context.Context, id gidx.PrefixedID) (*ServerMotherboardTypeDeletePayload, error) {
	panic(fmt.Errorf("not implemented: ServerMotherboardTypeDelete - serverMotherboardTypeDelete"))
}

// ServerMotherboardType is the resolver for the serverMotherboardType field.
func (r *queryResolver) ServerMotherboardType(ctx context.Context, id gidx.PrefixedID) (*generated.ServerMotherboardType, error) {
	panic(fmt.Errorf("not implemented: ServerMotherboardType - serverMotherboardType"))
}
