package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ServerMotherboard is the resolver for the serverMotherboard field.
func (r *mutationResolver) ServerMotherboard(ctx context.Context, input generated.CreateServerMotherboardInput) (*ServerMotherboardCreatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerMotherboard - serverMotherboard"))
}

// ServerMotherboardUpdate is the resolver for the serverMotherboardUpdate field.
func (r *mutationResolver) ServerMotherboardUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerMotherboardInput) (*ServerMotherboardUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerMotherboardUpdate - serverMotherboardUpdate"))
}

// ServerMotherboardDelete is the resolver for the serverMotherboardDelete field.
func (r *mutationResolver) ServerMotherboardDelete(ctx context.Context, id gidx.PrefixedID) (*ServerMotherboardDeletePayload, error) {
	panic(fmt.Errorf("not implemented: ServerMotherboardDelete - serverMotherboardDelete"))
}

// ServerMotherboard is the resolver for the serverMotherboard field.
func (r *queryResolver) ServerMotherboard(ctx context.Context, id gidx.PrefixedID) (*generated.ServerMotherboard, error) {
	panic(fmt.Errorf("not implemented: ServerMotherboard - serverMotherboard"))
}
