package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ServerNetworkCardType is the resolver for the serverNetworkCardType field.
func (r *mutationResolver) ServerNetworkCardType(ctx context.Context, input generated.CreateServerNetworkCardTypeInput) (*ServerNetworkCardTypeCreatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerNetworkCardType - serverNetworkCardType"))
}

// ServerNetworkCardTypeUpdate is the resolver for the serverNetworkCardTypeUpdate field.
func (r *mutationResolver) ServerNetworkCardTypeUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerNetworkCardTypeInput) (*ServerNetworkCardTypeUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerNetworkCardTypeUpdate - serverNetworkCardTypeUpdate"))
}

// ServerNetworkCardTypeDelete is the resolver for the serverNetworkCardTypeDelete field.
func (r *mutationResolver) ServerNetworkCardTypeDelete(ctx context.Context, id gidx.PrefixedID) (*ServerNetworkCardTypeDeletePayload, error) {
	panic(fmt.Errorf("not implemented: ServerNetworkCardTypeDelete - serverNetworkCardTypeDelete"))
}

// ServerNetworkCardType is the resolver for the serverNetworkCardType field.
func (r *queryResolver) ServerNetworkCardType(ctx context.Context, id gidx.PrefixedID) (*generated.ServerNetworkCardType, error) {
	panic(fmt.Errorf("not implemented: ServerNetworkCardType - serverNetworkCardType"))
}
