package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ServerNetworkPort is the resolver for the serverNetworkPort field.
func (r *mutationResolver) ServerNetworkPort(ctx context.Context, input generated.CreateServerNetworkPortInput) (*ServerNetworkPortCreatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerNetworkPort - serverNetworkPort"))
}

// ServerNetworkPortUpdate is the resolver for the serverNetworkPortUpdate field.
func (r *mutationResolver) ServerNetworkPortUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerNetworkPortInput) (*ServerNetworkPortUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerNetworkPortUpdate - serverNetworkPortUpdate"))
}

// ServerNetworkPortDelete is the resolver for the serverNetworkPortDelete field.
func (r *mutationResolver) ServerNetworkPortDelete(ctx context.Context, id gidx.PrefixedID) (*ServerNetworkPortDeletePayload, error) {
	panic(fmt.Errorf("not implemented: ServerNetworkPortDelete - serverNetworkPortDelete"))
}

// ServerNetworkPort is the resolver for the serverNetworkPort field.
func (r *queryResolver) ServerNetworkPort(ctx context.Context, id gidx.PrefixedID) (*generated.ServerNetworkPort, error) {
	panic(fmt.Errorf("not implemented: ServerNetworkPort - serverNetworkPort"))
}
