package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ServerNetworkCard is the resolver for the serverNetworkCard field.
func (r *mutationResolver) ServerNetworkCard(ctx context.Context, input generated.CreateServerNetworkCardInput) (*ServerNetworkCardCreatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerNetworkCard - serverNetworkCard"))
}

// ServerNetworkCardUpdate is the resolver for the serverNetworkCardUpdate field.
func (r *mutationResolver) ServerNetworkCardUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerNetworkCardInput) (*ServerNetworkCardUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerNetworkCardUpdate - serverNetworkCardUpdate"))
}

// ServerNetworkCardDelete is the resolver for the serverNetworkCardDelete field.
func (r *mutationResolver) ServerNetworkCardDelete(ctx context.Context, id gidx.PrefixedID) (*ServerNetworkCardDeletePayload, error) {
	panic(fmt.Errorf("not implemented: ServerNetworkCardDelete - serverNetworkCardDelete"))
}

// ServerNetworkCard is the resolver for the serverNetworkCard field.
func (r *queryResolver) ServerNetworkCard(ctx context.Context, id gidx.PrefixedID) (*generated.ServerNetworkCard, error) {
	panic(fmt.Errorf("not implemented: ServerNetworkCard - serverNetworkCard"))
}
