package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ServerPowerSupplyType is the resolver for the serverPowerSupplyType field.
func (r *mutationResolver) ServerPowerSupplyType(ctx context.Context, input generated.CreateServerPowerSupplyTypeInput) (*ServerPowerSupplyTypeCreatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerPowerSupplyType - serverPowerSupplyType"))
}

// ServerPowerSupplyTypeUpdate is the resolver for the serverPowerSupplyTypeUpdate field.
func (r *mutationResolver) ServerPowerSupplyTypeUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerPowerSupplyTypeInput) (*ServerPowerSupplyTypeUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerPowerSupplyTypeUpdate - serverPowerSupplyTypeUpdate"))
}

// ServerPowerSupplyTypeDelete is the resolver for the serverPowerSupplyTypeDelete field.
func (r *mutationResolver) ServerPowerSupplyTypeDelete(ctx context.Context, id gidx.PrefixedID) (*ServerPowerSupplyTypeDeletePayload, error) {
	panic(fmt.Errorf("not implemented: ServerPowerSupplyTypeDelete - serverPowerSupplyTypeDelete"))
}

// ServerPowerSupplyType is the resolver for the serverPowerSupplyType field.
func (r *queryResolver) ServerPowerSupplyType(ctx context.Context, id gidx.PrefixedID) (*generated.ServerPowerSupplyType, error) {
	panic(fmt.Errorf("not implemented: ServerPowerSupplyType - serverPowerSupplyType"))
}
