package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"go.infratographer.com/server-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// ServerCreate is the resolver for the serverCreate field.
func (r *mutationResolver) ServerCreate(ctx context.Context, input generated.CreateServerInput) (*ServerCreatePayload, error) {
	srv, err := r.client.Server.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &ServerCreatePayload{Server: srv}, nil
}

// ServerUpdate is the resolver for the serverUpdate field.
func (r *mutationResolver) ServerUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateServerInput) (*ServerUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: ServerUpdate - serverUpdate"))
}

// ServerDelete is the resolver for the serverDelete field.
func (r *mutationResolver) ServerDelete(ctx context.Context, id gidx.PrefixedID) (*ServerDeletePayload, error) {
	panic(fmt.Errorf("not implemented: ServerDelete - serverDelete"))
}

// Server is the resolver for the server field.
func (r *queryResolver) Server(ctx context.Context, id gidx.PrefixedID) (*generated.Server, error) {
	panic(fmt.Errorf("not implemented: Server - server"))
}
